apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: fhndatabricks.databricks.org
  labels:
     provider: databricks-crossplane
spec:
  resources:
    - name: test-databricks-crossplane 
      base:
        apiVersion: databricks.azure.upbound.io/v1beta1
        kind: Workspace
        metadata:
          annotations:
            meta.upbound.io/example-id: databricks/v1beta1/workspace
          labels:
            testing.upbound.io/example-name: test-databricks-crossplane
          name: test-databricks-crossplane 
        spec:
          providerConfigRef:
            name: azure-provider-config
          forProvider:
            location: blah-region 
            #resourceGroupName: blah-rg
            resourceGroupNameSelector:
                matchLabels:
                        purpose: crossplane-poc
            sku: trial 
            tags:
              purpose: poc
              deployment-type: crossplane
            managedResourceGroupName: rg-databricks-poc-2 
            customParameters:
                - virtualNetworkId: blah
                  publicSubnetNetworkSecurityGroupAssociationId: nsg-id # patched
                  privateSubnetNetworkSecurityGroupAssociationId: nsg-id # patched
                  noPublicIp: true 
                  privateSubnetNameSelector: 
                        matchControllerRef: true
                        matchLabels:
                                purpose: pricrossplane
                  publicSubnetNameSelector: 
                        matchControllerRef: true
                        matchLabels:
                                purpose: pubcrossplane

      patches:
        - fromFieldPath: "spec.parameters.resourceGroupName"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - fromFieldPath: "spec.parameters.mngedResourceGroupName"
          toFieldPath: "spec.forProvider.managedResourceGroupName"
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.resources.name"
        - fromFieldPath: "metadata.labels.mngedResourceGroupName"
          toFieldPath: "spec.forProvider.managedResourceGroupName"
        - fromFieldPath: "status.nsg.id"
          toFieldPath: "spec.forProvider.customParameters[0].privateSubnetNetworkSecurityGroupAssociationId"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "status.nsg.id"
          toFieldPath: "spec.forProvider.customParameters[0].publicSubnetNetworkSecurityGroupAssociationId"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.parameters.virtualNetworkId"
          toFieldPath: "spec.forProvider.customParameters[0].virtualNetworkId"

    - name: subnet-004
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        metadata:
          #name: snet-fhn-apidal-nonprod-qa-wcus-004
          labels:
                  purpose: pricrossplane
                  subnet-purpose: crossplane-poc 
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            delegation:
              - name: pri-delegation
                serviceDelegation:
                  - name: Microsoft.Databricks/workspaces
            addressPrefixes:
              - blah 
            resourceGroupName: vnet-rg 
            virtualNetworkName: vnets-001

    - name: subnet-005 
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        metadata:
          #name: snet-fhn-apidal-nonprod-qa-wcus-005
          labels:
                  purpose: pubcrossplane
                  subnet-purpose: crossplane-poc 
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            delegation:
              - name: pub-delegation
                serviceDelegation:
                  - name: Microsoft.Databricks/workspaces
            addressPrefixes:
              - blah 
            resourceGroupName: vnet-rg 
            virtualNetworkName: vent-001

    - name: pub-databricks-nsg 
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: SubnetNetworkSecurityGroupAssociation
        metadata:
          labels:
                  purpose: crossplane-poc
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            networkSecurityGroupIdSelector: 
              matchLabels:
                  purpose: databricks-nsg-crossplane
            subnetIdSelector:
              matchLabels:
                  purpose: pubcrossplane

    - name: pri-databricks-nsg
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: SubnetNetworkSecurityGroupAssociation
        metadata:
          labels:
                  purpose: crossplane-poc
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            networkSecurityGroupIdSelector: 
              matchLabels:
                  purpose: databricks-nsg-crossplane
            subnetIdSelector:
              matchLabels:
                  purpose: pricrossplane

    - name: databricks-nsg 
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          #annotations: 
          #  crossplane.io/external-name: databricks-nsg
          labels:
                  purpose: databricks-nsg-crossplane
        spec:
          providerConfigRef:
            name: azure-provider-config
          forProvider:
            location: blah-region 
            resourceGroupName: blah-rg
            #resourceGroupNameSelector:
            #  matchLabels:
            #    testing.upbound.io/example-name: virthubrtableroute-rg
            securityRule:
                #Removed
      patches:
        - fromFieldPath: "spec.parameters.databricksNSGName"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider
          toFieldPath: status.nsg
  compositeTypeRef:
    apiVersion: databricks.org/v1alpha1
    kind: FHNDataBricks
