apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: fhndatabricks.databricks.org
  labels:
     provider: databricks-crossplane
spec:
  resources:
    - name: test-databricks-crossplane 
      base:
        apiVersion: databricks.azure.upbound.io/v1beta1
        kind: Workspace
        metadata:
          annotations:
            meta.upbound.io/example-id: databricks/v1beta1/workspace
          labels:
            testing.upbound.io/example-name: test-databricks-crossplane
          name: test-databricks-crossplane 
        spec:
          providerConfigRef:
            name: azure-provider-config
          forProvider:
            location: West Central US 
            #resourceGroupName: rg-crossplane-poc-2
            resourceGroupNameSelector:
                matchLabels:
                        purpose: crossplane-poc
            sku: trial 
            tags:
              purpose: poc
              deployment-type: crossplane
            managedResourceGroupName: rg-databricks-poc-2 
            customParameters:
                - virtualNetweorkId: blah
                  publicSubnetNetworkSecurityGroupAssociationId: blah
                  privateSubnetNetworkSecurityGroupAssociationId: blah
                  noPublicIp: true 
                  privateSubnetNameSelector: 
                        matchControllerRef: true
                        matchLabels:
                                purpose: pricrossplane
                  publicSubnetNameSelector: 
                        matchControllerRef: true
                        matchLabels:
                                purpose: pubcrossplane

      patches:
        - fromFieldPath: "spec.parameters.resourceGroupName"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - fromFieldPath: "spec.parameters.mngedResourceGroupName"
          toFieldPath: "spec.forProvider.managedResourceGroupName"
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.resources.name"
        - fromFieldPath: "metadata.labels.mngedResourceGroupName"
          toFieldPath: "spec.forProvider.managedResourceGroupName"
        - fromFieldPath: "spec.parameters.privateSubnetNetworkSecurityGroupAssociationId"
          toFieldPath: "spec.forProvider.customParameters[0].privateSubnetNetworkSecurityGroupAssociationId"
        - fromFieldPath: "spec.parameters.publicSubnetNetworkSecurityGroupAssociationId"
          toFieldPath: "spec.forProvider.customParameters[0].publicSubnetNetworkSecurityGroupAssociationId"
        - fromFieldPath: "spec.parameters.virtualNetworkId"
          toFieldPath: "spec.forProvider.customParameters[0].virtualNetworkId"

    - name: snet-fhn-apidal-nonprod-qa-wcus-004
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        metadata:
          #name: snet-fhn-apidal-nonprod-qa-wcus-004
          labels:
                  purpose: pricrossplane
                  subnet-purpose: crossplane-poc 
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            delegation:
              - name: pri-delegation
                serviceDelegation:
                  - name: Microsoft.Databricks/workspaces
            addressPrefixes:
              - 100.64.15.0/25
            resourceGroupName: rg-fhn-apidal-nonprod 
            virtualNetworkName: vnet-fhn-apidal-nonprod-wcus-001

    - name: snet-fhn-apidal-nonprod-qa-wcus-005
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        metadata:
          #name: snet-fhn-apidal-nonprod-qa-wcus-005
          labels:
                  purpose: pubcrossplane
                  subnet-purpose: crossplane-poc 
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            delegation:
              - name: pub-delegation
                serviceDelegation:
                  - name: Microsoft.Databricks/workspaces
            addressPrefixes:
              - 100.64.15.128/25
            resourceGroupName: rg-fhn-apidal-nonprod 
            virtualNetworkName: vnet-fhn-apidal-nonprod-wcus-001

    - name: pub-databricks-nsg 
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: SubnetNetworkSecurityGroupAssociation
        metadata:
          labels:
                  purpose: crossplane-poc
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            #networkSecurityGroupId: /subscriptions/d076aac9-929f-4e58-b843-80641e7f7f15/resourceGroups/rg-crossplane-poc-2/providers/Microsoft.Network/networkSecurityGroups/databricksnsgekrhzk3ezyrqu 
            networkSecurityGroupIdSelector: 
              matchLabels:
                  purpose: databricks-nsg-crossplane
            subnetIdSelector:
              matchLabels:
                  purpose: pubcrossplane

    - name: pri-databricks-nsg
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: SubnetNetworkSecurityGroupAssociation
        metadata:
          labels:
                  purpose: crossplane-poc
        spec:
          providerConfigRef:
             name: azure-provider-config
          forProvider:
            #networkSecurityGroupId: /subscriptions/d076aac9-929f-4e58-b843-80641e7f7f15/resourceGroups/rg-crossplane-poc-2/providers/Microsoft.Network/networkSecurityGroups/databricksnsgekrhzk3ezyrqu 
            networkSecurityGroupIdSelector: 
              matchLabels:
                  purpose: databricks-nsg-crossplane
            subnetIdSelector:
              matchLabels:
                  purpose: pricrossplane

    - name: databricks-nsg 
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          #annotations: 
          #  crossplane.io/external-name: databricks-nsg
          labels:
                  purpose: databricks-nsg-crossplane
        spec:
          providerConfigRef:
            name: azure-provider-config
          forProvider:
            location: West Central US 
            resourceGroupName: rg-crossplane-poc-2
            #resourceGroupNameSelector:
            #  matchLabels:
            #    testing.upbound.io/example-name: virthubrtableroute-rg
            securityRule:
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-worker-inbound"
                      access:  "Allow"
                      description: "Required for worker nodes communication within a cluster."
                      protocol: "*"
                      sourcePortRange: "*"
                      destinationPortRange: "*"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "VirtualNetwork"
                      priority: 100
                      direction: "Inbound"
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-worker-inbound"
                      description: "Required for worker nodes communication within a cluster."
                      protocol: "*"
                      sourcePortRange: "*"
                      destinationPortRange: "*"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "VirtualNetwork"
                      access: "Allow"
                      priority: 100
                      direction: "Inbound"
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-worker-outbound"
                      description: "Required for worker nodes communication within a cluster."
                      protocol: "*"
                      sourcePortRange: "*"
                      destinationPortRange: "*"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "VirtualNetwork"
                      access: "Allow"
                      priority: 100
                      direction: "Outbound"
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-databricks-webapp"
                      description: "Required for workers communication with Databricks Webapp."
                      protocol: "Tcp"
                      sourcePortRange: "*"
                      destinationPortRange: "443"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "AzureDatabricks"
                      access: "Allow"
                      priority: 101
                      direction: "Outbound"
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-sql"
                      description: "Required for workers communication with Azure SQL services."
                      protocol: "Tcp"
                      sourcePortRange: "*"
                      destinationPortRange: "3306"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "Sql"
                      access: "Allow"
                      priority: 102
                      direction: "Outbound"
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-storage"
                      description: "Required for workers communication with Azure Storage services."
                      protocol: "Tcp"
                      sourcePortRange: "*"
                      destinationPortRange: "443"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "Storage"
                      access: "Allow"
                      priority: 103
                      direction: "Outbound"
                    - name: "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-eventhub"
                      description: "Required for worker communication with Azure Eventhub services."
                      protocol: "Tcp"
                      sourcePortRange: "*"
                      destinationPortRange: "9093"
                      sourceAddressPrefix: "VirtualNetwork"
                      destinationAddressPrefix: "EventHub"
                      access: "Allow"
                      priority: 104
                      direction: "Outbound"
      patches:
        - fromFieldPath: "spec.parameters.databricksNSGName"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
  compositeTypeRef:
    apiVersion: databricks.org/v1alpha1
    kind: FHNDataBricks
