apiVersion: databricks.org/v1alpha1
kind: FHNDataBricks
metadata:
  name: xp-fhn-databricks-poc-2 
  namespace: crossplane-system
spec:
  parameters:
    databricksNSGName: databricks-poc-nsg
    virtualNetworkId: /subscriptions/d076aac9-929f-4e58-b843-80641e7f7f15/resourceGroups/rg-fhn-apidal-nonprod/providers/Microsoft.Network/virtualNetworks/vnet-fhn-apidal-nonprod-wcus-001
    privateSubnetNetworkSecurityGroupAssociationId: /subscriptions/d076aac9-929f-4e58-b843-80641e7f7f15/resourceGroups/rg-crossplane-poc-2/providers/Microsoft.Network/networkSecurityGroups/databricks-poc-nsg
    publicSubnetNetworkSecurityGroupAssociationId: /subscriptions/d076aac9-929f-4e58-b843-80641e7f7f15/resourceGroups/rg-crossplane-poc-2/providers/Microsoft.Network/networkSecurityGroups/databricks-poc-nsg
    resourceGroupName: rg-crossplane-poc-2
    mngedResourceGroupName: rg-databricks-poc-2
  compositionSelector:
    matchLabels:
      provider: databricks-crossplane 
